# trigger:
#   branches:
#     include:
#       - main  # Define your branch trigger (you can specify any branch)


# pool:
#   name: Default  # Your agent pool name
#   demands:
#     - agent.name -equals DART  # Ensure it uses the DART agent
# jobs:
#   - job: Liquibase
#     displayName: 'Run Liquibase Changes'
#     pool:
#       vmImage: 'ubuntu-latest'

#     steps:
#       - task: Checkout@1
#         displayName: 'Checkout repository'
        
#       - script: |
#           echo "Setting up Liquibase..."
#           mkdir -p $(changelogDir)
#         displayName: 'Setup changelog directory'

#       # Step 1: Generate Liquibase Changelog Diff (between two databases)
#       - script: |
#           echo "Running Liquibase to generate Diff Changelog..."
#           docker run --rm \
#             -v $(changelogDir):/liquibase/changelog \
#             $(liquibaseImage) \
#             --referenceUrl="jdbc:postgresql://junction.proxy.rlwy.net:38704/railway" \
#             --referenceUsername="postgres" \
#             --referencePassword="PZTcUieBZVvBuxkxfQJSRMeUFXZmdLFN" \
#             --url="jdbc:postgresql://junction.proxy.rlwy.net:33223/railway" \
#             --username="postgres" \
#             --password="oPgUTipUBnhQBqbWnRYpeaKCdNJKMXQp" \
#             --changeLogFile="/liquibase/changelog/changelog_diff.xml" \
#             diffChangeLog
#         displayName: 'Generate Diff Changelog'

#       # Step 2: List changelog files to check if it's created
#       - script: |
#           echo "Listing files in changelog directory:"
#           ls -l $(changelogDir)
#         displayName: 'List changelog directory'

#       # Step 3: Apply the changelog to the target database
#       - script: |
#           echo "Applying changelog to the target database..."
#           docker run --rm \
#             -v $(changelogDir):/liquibase/changelog \
#             $(liquibaseImage) \
#             --url="jdbc:postgresql://junction.proxy.rlwy.net:33223/railway" \
#             --username="postgres" \
#             --password="oPgUTipUBnhQBqbWnRYpeaKCdNJKMXQp" \
#             --changeLogFile="/liquibase/changelog/changelog_diff).xml" \
#             update
#         displayName: 'Apply Changelog to Database'

     
# trigger:
#   branches:
#     include:
#       - main

# pool:
#   name: Default

# variables:
#   liquibaseImage: liquibase/liquibase:4.30
#   # changelogDir: $(Build.SourcesDirectory)/changelog
#   # timestamp: $(Build.BuildId)  # Simplified timestamp for debugging

# jobs:
#   - job: Liquibase
#     displayName: 'Run Liquibase Changes'
#     pool:
#       vmImage: 'ubuntu-latest'

#     steps:
#       - task: Checkout@1
#         displayName: 'Checkout repository'
        
#       # Step 1: Setup changelog directory
#       - script: |
#           echo "Setting up Liquibase..."
#           # mkdir -p $(changelogDir)
#         displayName: 'Setup changelog directory'

#       # Step 2: Generate Diff Changelog
#       - script: |
#           echo "Running Liquibase to generate Diff Changelog..."
#           docker run --rm \
#             -v $(changelogDir):/liquibase/changelog \
#             $(liquibaseImage) \
#             --referenceUrl="jdbc:postgresql://junction.proxy.rlwy.net:38704/railway" \
#             --referenceUsername="postgres" \
#             --referencePassword="PZTcUieBZVvBuxkxfQJSRMeUFXZmdLFN" \
#             --url="jdbc:postgresql://junction.proxy.rlwy.net:33223/railway" \
#             --username="postgres" \
#             --password="oPgUTipUBnhQBqbWnRYpeaKCdNJKMXQp" \
#             --changeLogFile="/liquibase/changelog/changelog.xml" \
#             diffChangeLog
#         displayName: 'Generate Diff Changelog'

#       # Step 3: List files in changelog directory
#       - script: |
#           echo "Listing files in changelog directory:"
#           # ls -l $(changelogDir)
#         displayName: 'List changelog directory'


# trigger:
#   branches:
#     include:
#       - main

# pool:
#   name: Default  # Your agent pool name
#   demands:
#     - agent.name -equals DART  # Ensure it uses the DART agent

# variables:
#   system.debug: true
#   liquibaseImage: liquibase/liquibase:4.30
#   changelogDir: $(Build.SourcesDirectory)/changelog
#   timestamp: $(Build.BuildId)  # Simplified timestamp for debugging

# jobs:
#   - job: Liquibase
#     displayName: 'Run Liquibase Changes'


#     steps:
#       # - task: Checkout@1
#       #   displayName: 'Checkout repository'
        
#       # Step 1: Setup changelog directory
#       - script: |
#           echo "Setting up Liquibase..."
#           # mkdir -p $(Build.SourcesDirectory)/changelog
#         displayName: 'Setup changelog directory'

#       # Step 2: Generate Diff Changelog
#       - script: |
#           echo "Running Liquibase to generate Diff Changelog..."
#           docker run --rm \
#             -v $(changelogDir):/liquibase/changelog \
#             liquibase/liquibase:4.30 \
#             --referenceUrl="jdbc:postgresql://autorack.proxy.rlwy.net:50269/railway" \
#             --referenceUsername="postgres" \
#             --referencePassword="YfRHTcyFlfZzQSzAIjFNTuEecneeXNrC" \
#             --url="jdbc:postgresql://autorack.proxy.rlwy.net:26951/railway" \
#             --username="postgres" \
#             --password="xfttiOeikUERuTxAIEoNpMpuZFlAQxgv" \
#             --changeLogFile="/liquibase/changelog/changelog.xml" \
#             diffChangeLog
#         displayName: 'Generate Diff Changelog'

#       # Step 3: List files in changelog directory
#       - script: |
#           echo "Listing files in changelog directory:"
#           ls -l $(Build.SourcesDirectory)/changelog
#         displayName: 'List changelog directory'

# trigger:
#   branches:
#     include:
#       - main

# pool:
#   name: Default
#   demands:
#     - agent.name -equals DART

# variables:
#   system.debug: true
#   liquibaseImage: liquibase/liquibase:4.30
#   changelogDir: $(Build.SourcesDirectory)/changelog

# jobs:
#   - job: Liquibase
#     displayName: 'Run Liquibase Changes'
#     timeoutInMinutes: 30

#     steps:
#       - script: |
#           echo "Creating changelog directory..."
#           mkdir -p $(Build.SourcesDirectory)/changelog
#           ls -l $(Build.SourcesDirectory)
#         displayName: 'Setup changelog directory'

#       - script: |
#           echo "Running Liquibase to generate Diff Changelog..."
#           docker run --rm \
#             -v $(Build.SourcesDirectory)/changelog:/liquibase/changelog \
#             liquibase/liquibase:4.30 \
#             --referenceUrl="jdbc:postgresql://autorack.proxy.rlwy.net:50269/railway" \
#             --referenceUsername="postgres" \
#             --referencePassword="YfRHTcyFlfZzQSzAIjFNTuEecneeXNrC" \
#             --url="jdbc:postgresql://autorack.proxy.rlwy.net:26951/railway" \
#             --username="postgres" \
#             --password="xfttiOeikUERuTxAIEoNpMpuZFlAQxgv" \
#             --changeLogFile="/changelog/changelog.xml" \
#             diffChangeLog || true
#           echo "Command completed with exit code $?"
#         displayName: 'Generate Diff Changelog'

#       - script: |
#           echo "Listing files in changelog directory:"
#           ls -l $(Build.SourcesDirectory)/changelog
#         displayName: 'List changelog directory'

# trigger:
#   branches:
#     include:
#       - main

# pool:
#   name: Default  # Your agent pool name
#   demands:
#     - agent.name -equals DART  # Ensure it uses the DART agent

# variables:
#   system.debug: true
#   liquibaseImage: liquibase/liquibase:4.30
#   changelogDir: $(Build.SourcesDirectory)/changelog  # Path where changelog.xml will be saved
#   timestamp: $(Build.BuildId)  # Simplified timestamp for debugging

# jobs:
#   - job: Liquibase
#     displayName: 'Run Liquibase Changes'

#     steps:
#       # Step 1: Debug Permissions for Sources Directory
#       - script: |
#           echo "Debugging permissions for Build.SourcesDirectory..."
#           ls -ld $(Build.SourcesDirectory) || echo "Build.SourcesDirectory does not exist."
#         displayName: 'Check Sources Directory Permissions'

#       # Step 2: Create and Verify Changelog Directory
#       - script: |
#           echo "Creating changelog directory..."
#           mkdir -p $(changelogDir)
#           echo "Setting permissions for changelog directory..."
#           chmod -R 777 $(changelogDir)
#           echo "Testing write access to changelog directory..."
#           echo "Test file content" > $(changelogDir)/test_file.txt
#           echo "Directory contents after test write:"
#           ls -l $(changelogDir)
#         displayName: 'Setup and Test Changelog Directory'

#       # Step 3: Run Liquibase Diff Changelog Command
#       - script: |
#           echo "Running Liquibase to generate Diff Changelog..."
#           docker run --rm \
#             -v $(changelogDir):/liquibase/changelog \
#             $(liquibaseImage) \
#             --referenceUrl="jdbc:postgresql://autorack.proxy.rlwy.net:50269/railway" \
#             --referenceUsername="postgres" \
#             --referencePassword="YfRHTcyFlfZzQSzAIjFNTuEecneeXNrC" \
#             --url="jdbc:postgresql://autorack.proxy.rlwy.net:26951/railway" \
#             --username="postgres" \
#             --password="xfttiOeikUERuTxAIEoNpMpuZFlAQxgv" \
#             --changeLogFile="/liquibase/changelog/changelog.xml" \
#             diffChangeLog || true
#           echo "Liquibase Diff ChangeLog Command completed."
#           echo "Printing changelog.xml content..."
#           cat $(changelogDir)/changelog.xml || echo "changelog.xml not found in $(changelogDir)"
#         displayName: 'Generate and Print Diff Changelog'

#       # Step 4: List Files in Changelog Directory (Optional Debugging)
#       - script: |
#           echo "Listing files in changelog directory to verify output:"
#           ls -l $(changelogDir) || echo "Changelog directory is empty or inaccessible."
#         displayName: 'Verify Changelog Output'

#       # Step 5: Print Changelog File Content (Optional)
#       - script: |
#           echo "Printing changelog.xml file content:"
#           cat $(changelogDir)/changelog.xml || echo "changelog.xml file not found."
#         displayName: 'Print Changelog File Content (Optional)'

# trigger:
#   branches:
#     include:
#       - main

# pool:
#   name: Default  # Your agent pool name
#   demands:
#     - agent.name -equals DART  # Ensure it uses the DART agent

# variables:
#   system.debug: true
#   liquibaseImage: liquibase/liquibase:4.30
#   changelogDir: $(Build.SourcesDirectory)/changelog  # Path where changelog.xml will be saved
#   timestamp: $(Build.BuildId)  # Simplified timestamp for debugging

# jobs:
#   - job: Liquibase
#     displayName: 'Run Liquibase Changes'

#     steps:
#       # Step 1: Debug Permissions for Sources Directory
#       - script: |
#           echo "Debugging permissions for Build.SourcesDirectory..."
#           ls -ld $(Build.SourcesDirectory) || echo "Build.SourcesDirectory does not exist."
#         displayName: 'Check Sources Directory Permissions'

#       # Step 2: Create and Verify Changelog Directory
#       - script: |
#           echo "Creating changelog directory..."
#           mkdir -p $(changelogDir)
#           echo "Setting permissions for changelog directory..."
#           chmod -R 777 $(changelogDir)
#           echo "Testing write access to changelog directory..."
#           echo "Test file content" > $(changelogDir)/test_file.txt
#           echo "Directory contents after test write:"
#           ls -l $(changelogDir)
#         displayName: 'Setup and Test Changelog Directory'

#       # Step 3: Run Liquibase Diff Changelog Command
#       - script: |
#           echo "Running Liquibase to generate Diff Changelog..."
#           docker run --rm \
#             -v $(changelogDir):/liquibase/changelog \
#             $(liquibaseImage) \
#             --referenceUrl="jdbc:postgresql://autorack.proxy.rlwy.net:13915/railway" \
#             --referenceUsername="postgres" \
#             --referencePassword="sTYcQKTWYMepxVUMYsRKOgyeETTCsBYv" \
#             --url="jdbc:postgresql://junction.proxy.rlwy.net:30985/railway" \
#             --username="postgres" \
#             --password="TaLslJjADxfBXnjVdfZjCiEZQNGyuiVZ" \
#             --changeLogFile="/liquibase/changelog/changelog.xml" \
#             diffChangeLog || true
#           echo "Liquibase Diff ChangeLog Command completed."
#           echo "Printing changelog.xml content..."
#           cat $(changelogDir)/changelog.xml || echo "changelog.xml not found in $(changelogDir)"
#         displayName: 'Generate and Print Diff Changelog'

#       # Step 4: List Files in Changelog Directory (Optional Debugging)
#       - script: |
#           echo "Listing files in changelog directory to verify output:"
#           ls -l $(changelogDir) || echo "Changelog directory is empty or inaccessible."
#         displayName: 'Verify Changelog Output'

#       # Step 5: Print Changelog File Content (Optional)
#       - script: |
#           echo "Printing changelog.xml file content:"
#           cat $(changelogDir)/changelog.xml || echo "changelog.xml file not found."
#         displayName: 'Print Changelog File Content (Optional)'
      
#       # Step 6: Apply Changelog to Production Database
#       - script: |
#           echo "Applying Liquibase Changelog to production database..."
#           docker run --rm \
#             # -v $(changelogDir):/liquibase/changelog \
#             $(liquibaseImage) \
#             --url="jdbc:postgresql://junction.proxy.rlwy.net:30985/railway" \
#             --username="postgres" \
#             --password="TaLslJjADxfBXnjVdfZjCiEZQNGyuiVZ" \
#             --changeLogFile="/Users/aravindreddynarreddy/Downloads/myagent/_work/2/s/changelog/changelog.xml" \
#             update || exit 1
#           echo "Liquibase update applied successfully to production database."
#         displayName: 'Apply Diff Changelog to Production Database'
      # - script: |
      #     echo "Verifying changes applied to the production database..."
      #     docker run --rm \
      #       $(liquibaseImage) \
      #       --url="jdbc:postgresql://autorack.proxy.rlwy.net:26951/railway" \
      #       --username="postgres" \
      #       --password="xfttiOeikUERuTxAIEoNpMpuZFlAQxgv" \
      #       --changeLogFile="/liquibase/changelog/changelog.xml" \
      #       status
      #   displayName: 'Verify Changelog Status in Production Database'


trigger:
  branches:
    include:
      - main

pool:
  name: Default
  demands:
    - agent.name -equals DART

variables:
  system.debug: true
  liquibaseImage: liquibase/liquibase:4.30
  changelogDirTemp: $(Build.SourcesDirectory)/changelog-temp
  changelogDir: $(Build.SourcesDirectory)/changelog  # Temporary directory for changelog generation
  changelogFile: changelog/changelog.xml
  githubRepo: reddyaravind/liquibase  # Replace with your GitHub repository
  githubToken: $(GITHUB_TOKEN)  # GitHub Personal Access Token stored in Azure DevOps secrets
  buildId: $(Build.BuildId)

jobs:
  - job: GenerateChangelog
    displayName: 'Generate and Push Changelog'

    steps:
      # Step 1: Generate Liquibase Diff Changelog
      - script: |
          echo "Running Liquibase to generate Diff Changelog..."
          mkdir -p $(changelogDir)
          docker run --rm \
            -v $(changelogDir):/liquibase/changelog \
            $(liquibaseImage) \
            --referenceUrl="jdbc:postgresql://autorack.proxy.rlwy.net:13915/railway" \
            --referenceUsername="postgres" \
            --referencePassword="sTYcQKTWYMepxVUMYsRKOgyeETTCsBYv" \
            --url="jdbc:postgresql://junction.proxy.rlwy.net:30985/railway" \
            --username="postgres" \
            --password="TaLslJjADxfBXnjVdfZjCiEZQNGyuiVZ" \
            --changeLogFile="/liquibase/changelog/changelog.xml" \
            diffChangeLog || true
          echo "Liquibase Diff Changelog Command completed."
        displayName: 'Generate Changelog'

      # Step 2: Print Generated Changelog File Content
      - script: |
          echo "Printing the generated changelog.xml file content:"
          cat $(changelogDir)/changelog.xml || echo "changelog.xml not found!"
        displayName: 'Print Generated Changelog File'

      # Step 3: Push changelog.xml to GitHub using REST API
      - script: |
          echo "Pushing changelog.xml to GitHub repository..."
          base64File=$(base64 $(changelogDir)/changelog.xml | tr -d '\n')
          commitMessage="Build ID: $(buildId)"
          apiUrl="https://api.github.com/repos/$(githubRepo)/contents/$(changelogFile)"
          curl -X PUT \
            -H "Authorization: token $(githubToken)" \
            -H "Content-Type: application/json" \
            -d "{\"message\": \"${commitMessage}\", \"content\": \"${base64File}\"}" \
            ${apiUrl} || exit 1
          echo "Changelog successfully pushed with commit message: ${commitMessage}"
        displayName: 'Push Changelog to GitHub'

  - job: ApplyChangelog
    displayName: 'Fetch and Apply Changelog to Production'
    dependsOn: GenerateChangelog
    condition: succeeded()

    steps:
      # Step 1: Fetch changelog.xml from GitHub using REST API
      - script: |
          echo "Fetching changelog.xml from GitHub repository..."
          apiUrl="https://api.github.com/repos/$(githubRepo)/contents/$(changelogFile)"
          response=$(curl -s -H "Authorization: token $(githubToken)" ${apiUrl})
          fileContent=$(echo $response | jq -r '.content' | base64 -d)
          echo "$fileContent" > $(changelogDirTemp)/changelog.xml
          echo "changelog.xml successfully fetched and saved."
        displayName: 'Fetch Changelog from GitHub'

      # Step 2: Print Fetched Changelog File Content
      - script: |
          echo "Printing the fetched changelog.xml file content:"
          cat $(changelogDirTemp)/changelog.xml || echo "changelog.xml not found!"
        displayName: 'Print Fetched Changelog File'

      # Step 3: Apply Changelog to Production Database
      - script: |
          echo "Applying Liquibase Changelog to production database..."
          docker run --rm \
            -v $(changelogDir):/liquibase/changelog \
            $(liquibaseImage) \
            --url="jdbc:postgresql://junction.proxy.rlwy.net:30985/railway" \
            --username="postgres" \
            --password="TaLslJjADxfBXnjVdfZjCiEZQNGyuiVZ" \
            --changeLogFile="$(changelogDirTemp)/changelog.xml" \
            update || exit 1
          echo "Liquibase update applied successfully to production database."
        displayName: 'Apply Changelog to Production'
