name: Liquibase CI/CD Pipeline

on:
  workflow_dispatch: # Allows manual triggering of the pipeline

jobs:
  liquibase-cicd:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: aravindreddynarreddy
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: staging_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U aravindreddynarreddy"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
    # Checkout the repository
    - name: Checkout Code
      uses: actions/checkout@v3

    # Wait for PostgreSQL service to be ready
    - name: Wait for PostgreSQL
      run: |
        for i in {1..10}; do
          pg_isready -h localhost -U aravindreddynarreddy && break
          sleep 5
        done

    # Run Liquibase diffChangeLog
    - name: Run Liquibase to Create Diff ChangeLog
      run: |
        docker run --rm \
          -v ${{ github.workspace }}:/liquibase/changelog \
          liquibase/liquibase \
          --referenceUrl="jdbc:postgresql://postgres:5432/staging_db" \
          --referenceUsername="aravindreddynarreddy" \
          --referencePassword="password" \
          --url="jdbc:postgresql://postgres:5432/sandbox_db" \
          --username="aravindreddynarreddy" \
          --password="password" \
          --changeLogFile="changelog_diff.xml" \
          diffChangeLog

    # Apply changes to the higher environment (sandbox_db)
    - name: Apply Changes to Higher Environment
      run: |
        docker run --rm \
          -v ${{ github.workspace }}:/liquibase/changelog \
          liquibase/liquibase \
          --url="jdbc:postgresql://postgres:5432/sandbox_db" \
          --username="aravindreddynarreddy" \
          --password="password" \
          --changeLogFile="changelog_diff.xml" \
          update

    # Generate a new changelog file from the higher environment (sandbox_db)
    - name: Generate New Changelog from Sandbox DB
      run: |
        docker run --rm \
          -v ${{ github.workspace }}:/liquibase/changelog \
          liquibase/liquibase \
          --url="jdbc:postgresql://postgres:5432/sandbox_db" \
          --username="aravindreddynarreddy" \
          --password="password" \
          --changeLogFile="changelog_prod_generated.xml" \
          generateChangeLog

    # Commit and push the new changelog file to GitHub
    - name: Push Changelog to GitHub
      run: |
        git config --global user.name "reddyaravind"
        git config --global user.email "reddyaravind838@gmail.com"
        git add changelog_prod_generated.xml
        git commit -m "Updated changelog"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
