name: Liquibase CI/CD Pipeline

on:
  workflow_dispatch: # Allows manual triggering of the pipeline

jobs:
  liquibase-cicd:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout Code
      uses: actions/checkout@v3

    # Generate Timestamp for Changelog File
    - name: Set Timestamp
      id: timestamp
      run: echo "TIMESTAMP=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV

    # Clean Previous Changelog Directory
    - name: Clean Changelog Directory
      run: |
        mkdir -p ${{ github.workspace }}/changelog
        rm -rf ${{ github.workspace }}/changelog/*

    # Generate Diff ChangeLog with Enhanced Debugging
    - name: Run Liquibase to Generate Diff ChangeLog
      run: |
        echo "Running Liquibase diffChangeLog command..."
        docker run --rm \
          --user root \
          -v ${{ github.workspace }}/changelog:/liquibase/changelog \
          liquibase/liquibase \
          --logLevel=debug \
          --referenceUrl="jdbc:postgresql://junction.proxy.rlwy.net:38704/railway" \
          --referenceUsername="postgres" \
          --referencePassword="PZTcUieBZVvBuxkxfQJSRMeUFXZmdLFN" \
          --url="jdbc:postgresql://junction.proxy.rlwy.net:33223/railway" \
          --username="postgres" \
          --password="oPgUTipUBnhQBqbWnRYpeaKCdNJKMXQp" \
          --changeLogFile="/tmp/changelog_diff_${{ env.TIMESTAMP }}.xml" \
          diffChangeLog || echo "Liquibase command failed"

        echo "Liquibase diffChangeLog completed."

    # Debug: List files in changelog directory
    - name: Verify Changelog Directory
      run: |
        echo "Listing files in changelog directory:"
        ls -l ${{ github.workspace }}/changelog
        echo "Checking if changelog file exists in /tmp"
        if [ -f "/tmp/changelog_diff_${{ env.TIMESTAMP }}.xml" ]; then
          echo "Changelog file saved at /tmp"
          cat /tmp/changelog_diff_${{ env.TIMESTAMP }}.xml
        else
          echo "No changelog file found in /tmp!"
        fi

    # Apply changes to production using the generated changelog file
    - name: Apply Changes to Production
      run: |
        docker run --rm \
          --user root \
          -v ${{ github.workspace }}/changelog:/liquibase/changelog \
          liquibase/liquibase \
          --url="jdbc:postgresql://junction.proxy.rlwy.net:33223/railway" \
          --username="postgres" \
          --password="oPgUTipUBnhQBqbWnRYpeaKCdNJKMXQp" \
          --changeLogFile="/tmp/changelog_diff_${{ env.TIMESTAMP }}.xml" \
          update
        echo "Changes applied successfully to production!"

    # Push the changelog file to GitHub
    - name: Push Changelog to GitHub
      run: |
        git config --global user.name "reddyaravind"
        git config --global user.email "reddyaravind838@gmail.com"
        git add changelog/changelog_diff_${{ env.TIMESTAMP }}.xml
        git commit -m "Save generated changelog_diff_${{ env.TIMESTAMP }}.xml"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
