name: Liquibase CI/CD Pipeline

on:
  workflow_dispatch: # Allows manual triggering of the pipeline

jobs:
  liquibase-cicd:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout Code
      uses: actions/checkout@v3

    # Set up Docker to use the Liquibase image
    - name: Run Liquibase Docker Container
      run: |
        docker run --rm \
          -v ${{ github.workspace }}:/liquibase/changelog \
          liquibase/liquibase \
          --referenceUrl="jdbc:postgresql://staging_db_host:5432/staging_db" \
          --referenceUsername=${{ secrets.DB_USERNAME }} \
          --referencePassword=${{ secrets.DB_PASSWORD }} \
          --url="jdbc:postgresql://prod_db_host:5432/sandbox_db" \
          --username=${{ secrets.DB_USERNAME }} \
          --password=${{ secrets.DB_PASSWORD }} \
          --changeLogFile="changelog_diff.xml" \
          diffChangeLog

    # Apply the changes to the production database
    - name: Apply Changes to Production
      run: |
        docker run --rm \
          -v ${{ github.workspace }}:/liquibase/changelog \
          liquibase/liquibase \
          --url="jdbc:postgresql://prod_db_host:5432/sandbox_db" \
          --username=${{ secrets.DB_USERNAME }} \
          --password=${{ secrets.DB_PASSWORD }} \
          --changeLogFile="changelog_diff.xml" \
          update

    # Generate a new changelog file from the production database
    - name: Generate New Changelog
      run: |
        docker run --rm \
          -v ${{ github.workspace }}:/liquibase/changelog \
          liquibase/liquibase \
          --url="jdbc:postgresql://prod_db_host:5432/sandbox_db" \
          --username=${{ secrets.DB_USERNAME }} \
          --password=${{ secrets.DB_PASSWORD }} \
          --changeLogFile="changelog_prod_generated.xml" \
          generateChangeLog

    # Commit and push the new changelog file to GitHub
    - name: Push Changelog to GitHub
      run: |
        git config --global user.name "reddyaravind"
        git config --global user.email "reddyaravind838@gmail.com"
        git init
        git add .
        git commit -m "Updated changelog"
        git branch -M main
        git remote add origin https://github.com/reddyaravind/liquibase.git
        git push -u origin main
      env:
        # Set GitHub token to allow pushing to the repository
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
