# name: Liquibase CI/CD Pipeline

# on:
#   workflow_dispatch: # Allows manual triggering of the pipeline

# jobs:
#   liquibase-cicd:
#     runs-on: ubuntu-latest

#     services:
#       postgres:
#         image: postgres:15
#         env:
#           POSTGRES_USER: aravindreddynarreddy
#           POSTGRES_PASSWORD: password
#           POSTGRES_DB: staging_db
#         ports:
#           - 5432:5432
#         options: >-
#           --health-cmd="pg_isready -U aravindreddynarreddy"
#           --health-interval=10s
#           --health-timeout=5s
#           --health-retries=3

#     steps:
#     # Checkout the repository
#     - name: Checkout Code
#       uses: actions/checkout@v3

#     # Wait for PostgreSQL service to be ready
#     - name: Wait for PostgreSQL
#       run: |
#         for i in {1..30}; do
#           if pg_isready -h localhost -p 5432 -U aravindreddynarreddy; then
#             echo "PostgreSQL is ready!"
#             break
#           fi
#           echo "Waiting for PostgreSQL..."
#           sleep 2
#         done

#     # Run Liquibase diffChangeLog
#     - name: Run Liquibase to Create Diff ChangeLog
#       run: |
#         docker run --rm \
#           -v ${{ github.workspace }}:/liquibase/changelog \
#           liquibase/liquibase \
#           --referenceUrl="jdbc:postgresql://localhost:5432/prod_db" \
#           --referenceUsername="aravindreddynarreddy" \
#           --referencePassword="password" \
#           --url="jdbc:postgresql://localhost:5432/sandbox" \
#           --username="aravindreddynarreddy" \
#           --password="password" \
#           --changeLogFile="changelog_diff.xml" \
#           diffChangeLog

#     # Apply changes to the higher environment (sandbox_db)
#     - name: Apply Changes to Higher Environment
#       run: |
#         docker run --rm \
#           -v ${{ github.workspace }}:/liquibase/changelog \
#           liquibase/liquibase \
#           --url="jdbc:postgresql://localhost:5432/sandbox" \
#           --username="aravindreddynarreddy" \
#           --password="password" \
#           --changeLogFile="changelog_diff.xml" \
#           update

#     # Generate a new changelog file from the higher environment (sandbox_db)
#     - name: Generate New Changelog from Sandbox DB
#       run: |
#         docker run --rm \
#           -v ${{ github.workspace }}:/liquibase/changelog \
#           liquibase/liquibase \
#           --url="jdbc:postgresql://localhost:5432/sandbox" \
#           --username="aravindreddynarreddy" \
#           --password="password" \
#           --changeLogFile="changelog_prod_generated.xml" \
#           generateChangeLog

#     # Commit and push the new changelog file to GitHub
#     - name: Push Changelog to GitHub
#       run: |
#         git config --global user.name "reddyaravind"
#         git config --global user.email "reddyaravind838@gmail.com"
#         git add changelog_prod_generated.xml
#         git commit -m "Updated changelog"
#         git push
#       env:
#         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}



name: Liquibase CI/CD Pipeline

on:
  push:
    branches:
      - main  # Trigger the pipeline on push to the main branch

jobs:
  generate-and-apply-changes:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Set environment variables (replace with actual values)
    - name: Set environment variables
      run: |
        echo "STAGING_DB_URL=postgresql://postgres:ThQNAfKRnLPpeLgJgDAkhQwVcEZfuHmH@autorack.proxy.rlwy.net:58854/railway" >> $GITHUB_ENV
        echo "STAGING_DB_USERNAME=postgres" >> $GITHUB_ENV
        echo "STAGING_DB_PASSWORD=ThQNAfKRnLPpeLgJgDAkhQwVcEZfuHmH" >> $GITHUB_ENV
        echo "PRODUCTION_DB_URL=postgresql://postgres:oebjeJFqRLeFcIBAziEJQsMKeLhUeRFc@junction.proxy.rlwy.net:59848/railway" >> $GITHUB_ENV
        echo "PRODUCTION_DB_USERNAME=postgres" >> $GITHUB_ENV
        echo "PRODUCTION_DB_PASSWORD=oebjeJFqRLeFcIBAziEJQsMKeLhUeRFc" >> $GITHUB_ENV
        echo "CHANGELOG_PATH=changelog_diff.xml" >> $GITHUB_ENV

    # Step 1: Generate the changelog file from the staging database
    - name: Generate Changelog from Staging Database
      run: |
        docker run --rm \
          -v ${{ github.workspace }}/changelog:/liquibase/changelog \
          liquibase/liquibase:4.30.0 \
          --url="${{ env.STAGING_DB_URL }}" \
          --username="${{ env.STAGING_DB_USERNAME }}" \
          --password="${{ env.STAGING_DB_PASSWORD }}" \
          --driver=org.postgresql.Driver \
          --changeLogFile="/liquibase/changelog/${{ env.CHANGELOG_PATH }}" \
          generateChangelog

    # Step 2: Apply the generated changelog to the production database
    - name: Apply Changes to Production Database
      run: |
        # Ensure the changelog file exists in the correct location inside the Docker container
        echo "Checking changelog file location inside the container"
        ls -alh ${{ github.workspace }}/changelog

        # Apply changes using the generated changelog file
        docker run --rm \
          -v ${{ github.workspace }}/changelog:/liquibase/changelog \
          liquibase/liquibase:4.30.0 \
          --url="${{ env.PRODUCTION_DB_URL }}" \
          --username="${{ env.PRODUCTION_DB_USERNAME }}" \
          --password="${{ env.PRODUCTION_DB_PASSWORD }}" \
          --changeLogFile="file:/liquibase/changelog/${{ env.CHANGELOG_PATH }}" \
          update
