# name: Liquibase CI/CD Pipeline

# on:
#   workflow_dispatch: # Allows manual triggering of the pipeline

# jobs:
#   liquibase-cicd:
#     runs-on: ubuntu-latest

#     services:
#       postgres:
#         image: postgres:15
#         env:
#           POSTGRES_USER: aravindreddynarreddy
#           POSTGRES_PASSWORD: password
#           POSTGRES_DB: staging_db
#         ports:
#           - 5432:5432
#         options: >-
#           --health-cmd="pg_isready -U aravindreddynarreddy"
#           --health-interval=10s
#           --health-timeout=5s
#           --health-retries=3

#     steps:
#     # Checkout the repository
#     - name: Checkout Code
#       uses: actions/checkout@v3

#     # Wait for PostgreSQL service to be ready
#     - name: Wait for PostgreSQL
#       run: |
#         for i in {1..30}; do
#           if pg_isready -h localhost -p 5432 -U aravindreddynarreddy; then
#             echo "PostgreSQL is ready!"
#             break
#           fi
#           echo "Waiting for PostgreSQL..."
#           sleep 2
#         done

#     # Run Liquibase diffChangeLog
#     - name: Run Liquibase to Create Diff ChangeLog
#       run: |
#         docker run --rm \
#           -v ${{ github.workspace }}:/liquibase/changelog \
#           liquibase/liquibase \
#           --referenceUrl="jdbc:postgresql://localhost:5432/prod_db" \
#           --referenceUsername="aravindreddynarreddy" \
#           --referencePassword="password" \
#           --url="jdbc:postgresql://localhost:5432/sandbox" \
#           --username="aravindreddynarreddy" \
#           --password="password" \
#           --changeLogFile="changelog_diff.xml" \
#           diffChangeLog

#     # Apply changes to the higher environment (sandbox_db)
#     - name: Apply Changes to Higher Environment
#       run: |
#         docker run --rm \
#           -v ${{ github.workspace }}:/liquibase/changelog \
#           liquibase/liquibase \
#           --url="jdbc:postgresql://localhost:5432/sandbox" \
#           --username="aravindreddynarreddy" \
#           --password="password" \
#           --changeLogFile="changelog_diff.xml" \
#           update

#     # Generate a new changelog file from the higher environment (sandbox_db)
#     - name: Generate New Changelog from Sandbox DB
#       run: |
#         docker run --rm \
#           -v ${{ github.workspace }}:/liquibase/changelog \
#           liquibase/liquibase \
#           --url="jdbc:postgresql://localhost:5432/sandbox" \
#           --username="aravindreddynarreddy" \
#           --password="password" \
#           --changeLogFile="changelog_prod_generated.xml" \
#           generateChangeLog

#     # Commit and push the new changelog file to GitHub
#     - name: Push Changelog to GitHub
#       run: |
#         git config --global user.name "reddyaravind"
#         git config --global user.email "reddyaravind838@gmail.com"
#         git add changelog_prod_generated.xml
#         git commit -m "Updated changelog"
#         git push
#       env:
#         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}



name: Liquibase CI/CD Pipeline

on:
  workflow_dispatch: # Allows manual triggering of the pipeline

jobs:
  liquibase-cicd:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout Code
      uses: actions/checkout@v3

    # Step 2: Generate Diff ChangeLog and Save Path to Static Variable
    - name: Generate Diff ChangeLog
      id: generate_diff
      run: |
        mkdir -p ${{ github.workspace }}/changelog
        changelog_path="${{ github.workspace }}/changelog/changelog_diff.xml"
        
        docker run --rm \
          -v ${{ github.workspace }}/changelog:/liquibase/changelog \
          liquibase/liquibase \
          --referenceUrl="jdbc:postgresql://autorack.proxy.rlwy.net:58854/railway" \
          --referenceUsername="postgres" \
          --referencePassword="ThQNAfKRnLPpeLgJgDAkhQwVcEZfuHmH" \
          --url="jdbc:postgresql://junction.proxy.rlwy.net:59848/railway" \
          --username="postgres" \
          --password="oebjeJFqRLeFcIBAziEJQsMKeLhUeRFc" \
          --changeLogFile="/liquibase/changelog/changelog_diff.xml" \
          diffChangeLog

        echo "changelog_path1=$changelog_path" >> $GITHUB_ENV
        echo "Diff ChangeLog generated successfully at $changelog_path"

    # Step 3: Verify the Generated ChangeLog File
    - name: Verify ChangeLog File
      run: |
        if [ -f "${{ github.workspace }}/changelog/changelog_diff.xml" ]; then
          echo "Changelog file exists and is ready for use."
        else
          echo "Changelog file not found!" && exit 1
        fi

    # Step 4: Apply Changes to Production Database
    - name: Apply Changes to Production
      run: |
        mkdir -p ${{ github.workspace }}/changelog
        changelog_path="${{ github.workspace }}/changelog/changelog_diff.xml"
        
        docker run --rm \
          -v ${{ github.workspace }}/changelog:/liquibase/changelog \
          liquibase/liquibase \
          --url="jdbc:postgresql://junction.proxy.rlwy.net:59848/railway" \
          --username="postgres" \
          --password="oebjeJFqRLeFcIBAziEJQsMKeLhUeRFc" \
          --changeLogFile="${{ env.changelog_path1 }}" \
          update

        echo "Changes applied successfully to the production database."

    # Step 5: Cleanup (Optional)
    - name: Cleanup
      run: |
        rm -rf ${{ github.workspace }}/changelog
        echo "Temporary changelog files cleaned up."

