name: Liquibase CI/CD Pipeline

on:
  workflow_dispatch: # Allows manual trigger of the workflow.

jobs:
  liquibase-workflow:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Generate diff changelog
    - name: Generate diff changelog
      run: |
        docker run --rm \
          -v $(pwd):/liquibase/changelog \
          liquibase/liquibase \
          --referenceUrl=${{ secrets.LOWER_DB_URL }} \
          --referenceUsername=${{ secrets.DB_USERNAME }} \
          --referencePassword=${{ secrets.DB_PASSWORD }} \
          --url=${{ secrets.HIGHER_DB_URL }} \
          --username=${{ secrets.DB_USERNAME }} \
          --password=${{ secrets.DB_PASSWORD }} \
          --changeLogFile=/liquibase/changelog/diff_changelog.xml \
          diffChangeLog

    # Step 3: Apply changes to higher environment
    - name: Apply changes to higher environment
      run: |
        docker run --rm \
          -v $(pwd):/liquibase/changelog \
          liquibase/liquibase \
          --url=${{ secrets.HIGHER_DB_URL }} \
          --username=${{ secrets.DB_USERNAME }} \
          --password=${{ secrets.DB_PASSWORD }} \
          --changeLogFile=/liquibase/changelog/diff_changelog.xml \
          update

    # Step 4: Generate new changelog from the higher environment
    - name: Generate new changelog
      run: |
        docker run --rm \
          -v $(pwd):/liquibase/changelog \
          liquibase/liquibase \
          --url=${{ secrets.HIGHER_DB_URL }} \
          --username=${{ secrets.DB_USERNAME }} \
          --password=${{ secrets.DB_PASSWORD }} \
          --changeLogFile=/liquibase/changelog/new_changelog.xml \
          generateChangeLog

    # Step 5: Push new changelog to GitHub
    - name: Push new changelog to GitHub
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add .
        git commit -m "Add new changelog from higher environment"
        git push origin ${{ github.ref }}
