name: Update Production Database

on:
  workflow_dispatch: # Allows manual triggering of the pipeline

jobs:
  update-production-db:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout Repository
      uses: actions/checkout@v3

    # Debug: Ensure changelog file exists in the workspace
    - name: Debug Changelog File
      run: |
        echo "Current working directory: $(pwd)"
        echo "Listing all files in workspace:"
        ls -lR ${{ github.workspace }}
        echo "Listing files in changelog directory:"
        ls -l ${{ github.workspace }}/changelog
        cat ${{ github.workspace }}/changelog/changelog_diff.xml || echo "changelog_diff.xml is missing"

    # Debug: Verify Docker volume mount
    - name: Debug Docker Volume Mount
      run: |
        docker run --rm \
          -v ${{ github.workspace }}/changelog:/liquibase/changelog \
          liquibase/liquibase \
          ls -l /liquibase/changelog

    # Apply changes to the production database
    - name: Apply Changes to Production
      run: |
        docker run --rm \
          -v ${{ github.workspace }}/changelog:/liquibase/changelog \
          liquibase/liquibase \
          --url="jdbc:postgresql://junction.proxy.rlwy.net:18143/railway" \
          --username="postgres" \
          --password="mETBgLqbGkxManJuOUtqRbdyZQmpRacV" \
          --changeLogFile="/liquibase/changelog/changelog_diff.xml" \
          update
